CRS.WebUI/Controllers/ConferenceRoomsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
//Need to add this for the Processor to work
//PM>Install-Package EntityFramework -Version 6.1.3 -projectname CRS.WebUI

namespace CRS.WebUI.Controllers
{
    public class ConferenceRoomsController : Controller
    {
        private CRS.Domain.ConcreteProcessors.ProcessConferenceRooms objProcessCR;
  
        public ConferenceRoomsController()
        {
            objProcessCR = new CRS.Domain.ConcreteProcessors.ProcessConferenceRooms();
        }

        // GET: ConferenceRooms
        public ActionResult Index()
        {
            return View(( IEnumerable<CRS.Domain.ConcreteEntities.ConferenceRoom>)objProcessCR.ConferenceRooms);
        }

        //RR Final, I did not provide any Detail support
        public ActionResult ConferenceRoomDetails(int SelectedConferenceRoomID)
        {
            CRS.Domain.Abstract.IConferenceRoom objSelectedConferenceRoom = objProcessCR.ConferenceRooms.FirstOrDefault(ID => ID.ConferenceRoomID == SelectedConferenceRoomID);
            return View(objSelectedConferenceRoom);
        } 

        [HttpGet]
        public ViewResult Insert()
        {
            return View(new CRS.Domain.ConcreteEntities.ConferenceRoom());
        }

        [HttpPost]
        public ActionResult Insert(CRS.Domain.ConcreteEntities.ConferenceRoom ConfernceRoom)
        {
            if (ModelState.IsValid)
            {
                objProcessCR.InsConferenceRooms(ConfernceRoom);
                return RedirectToAction("Index");
            }
            else
            {
                // there is something wrong with the data values
                return View(ConfernceRoom);
            }
        }

       

        [HttpGet]
        public ViewResult Update(int selectedCRID)
        {
            //This needs to be able to handle ConferenceRoom ID then populate fields with ConfRoom to update
            CRS.Domain.Abstract.IConferenceRoom objSelectedConferenceRoom = objProcessCR.ConferenceRooms.FirstOrDefault(ID => ID.ConferenceRoomID == selectedCRID);
            return View(objSelectedConferenceRoom);
        }

        [HttpPost]
        public ActionResult Update(CRS.Domain.ConcreteEntities.ConferenceRoom conferenceRoom)
        {
            if (ModelState.IsValid)
            {
                objProcessCR.UpdConferenceRooms(conferenceRoom);
                TempData["Message"] = string.Format("Conference Room {0} was updated!", conferenceRoom.ConferenceRoomID);
                return RedirectToAction("Index");
            }
            else
            {
                // there is something wrong with the data values
                return View(conferenceRoom);
            }
        }

        [HttpGet]
        public ViewResult Delete()
        {
            return View(new CRS.Domain.ConcreteEntities.ConferenceRoom());
        }

        [HttpPost]
        public ActionResult Delete(int conferenceRmID)
        {

            if (ModelState.IsValid)
            {

                objProcessCR.pDelConferenceRooms(conferenceRmID);
                TempData["Message"] = string.Format("Conference Room {0} was deleted!", conferenceRmID); // RR Final Did not provide message support
                return RedirectToAction("Index");
            }
            else
            {
                // there is something wrong with the data values
                return View(conferenceRmID);
                //return View();
            }
        }
    }
}

CRS.WebUI/Controllers/MeetingRoomAttendeesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CRS.WebUI.Controllers
{
    public class MeetingRoomAttendeesController : Controller
    {
        private CRS.Domain.ConcreteProcessors.ProcessMeetingRoomAttendees objProcessMRA;
  
        public MeetingRoomAttendeesController()
        {
            objProcessMRA = new CRS.Domain.ConcreteProcessors.ProcessMeetingRoomAttendees();
        }

        // GET: ConferenceRooms
        public ActionResult Index(int selectedMeetingID)
        {
            var objSelectedMeeting = objProcessMRA.MeetingRoomAttendees.Where(ID => ID.MeetingID == selectedMeetingID);
            TempData["SelectedMeetingID"] = selectedMeetingID;
            return View( objSelectedMeeting);
        }

        [Authorize]
        public ActionResult ManagerOverview()
        {
            return View((IEnumerable<CRS.Domain.Abstract.IMeetingRoomAttendee>)objProcessMRA.MeetingRoomAttendees);
        }

        //[HttpGet]
        //public ViewResult Insert()
        //{
        //    return View(new CRS.Domain.ConcreteEntities.MeetingRoomAttendee());
        //}

        //[HttpPost]
        //public ActionResult Insert(CRS.Domain.ConcreteEntities.MeetingRoomAttendee meetingrmAttendee)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        CRS.Domain.ConcreteProcessors.ProcessMeetingRoomAttendees objProcessor;
        //        objProcessor = new CRS.Domain.ConcreteProcessors.ProcessMeetingRoomAttendees();
        //        objProcessor.MeetingRoomAttendees = meetingrmAttendee;
        //        return RedirectToAction("Index");
        //    }
        //    else
        //    {
        //        // there is something wrong with the data values
        //        return View(meetingrmAttendee);
        //    }
        //}

        //[HttpGet]
        //public ViewResult Update()
        //{
        //    return View(new CRS.Domain.ConcreteEntities.Meeting());
        //}

        //[HttpPost]
        //public ActionResult Update(CRS.Domain.ConcreteEntities.Meeting meeting)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        CRS.Domain.ConcreteProcessors.ProcessMeetings objProcessor;
        //        objProcessor = new CRS.Domain.ConcreteProcessors.ProcessMeetings();
        //        objProcessor.pUpdMeetings(meeting);
        //        return RedirectToAction("Index");
        //    }
        //    else
        //    {
        //        // there is something wrong with the data values
        //        return View(meeting);
        //    }
        //}

        //[HttpGet]
        //public ViewResult Delete()
        //{
        //    return View(new CRS.Domain.ConcreteEntities.Meeting());
        //}

        //[HttpPost]
        //public ActionResult Delete(CRS.Domain.ConcreteEntities.Meeting meeting)
        //{

        //    if (ModelState.IsValid)
        //    {
        //        CRS.Domain.ConcreteProcessors.ProcessMeetings objProcessor;
        //        objProcessor = new CRS.Domain.ConcreteProcessors.ProcessMeetings();
        //        objProcessor.pDelMeetings(meeting);
        //        return RedirectToAction("Index");
        //    }
        //    else
        //    {
        //        // there is something wrong with the data values
        //        return View(meeting);
        //        //return View();
        //    }
        //}
    }
}

CRS.WebUI/Controllers/MeetingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CRS.WebUI.Controllers
{
    [Authorize]
    public class MeetingsController : Controller
    {
        private CRS.Domain.Abstract.IProcessMeetings objProcessM;
  
        public MeetingsController()
        {
            objProcessM = new CRS.Domain.ConcreteProcessors.ProcessMeetings();
        }

        // GET: ConferenceRooms
        public ActionResult Index()
        {
            return View(( IEnumerable<CRS.Domain.ConcreteEntities.Meeting>)objProcessM.Meetings);
        }

        [HttpGet]
        public ViewResult Insert()
        {
            return View(new CRS.Domain.ConcreteEntities.Meeting());
        }

        [HttpPost]
        public ActionResult Insert(CRS.Domain.ConcreteEntities.Meeting meeting)
        {
            if (ModelState.IsValid)
            {   
                CRS.Domain.ConcreteProcessors.ProcessMeetings objProcessor;
                objProcessor = new CRS.Domain.ConcreteProcessors.ProcessMeetings();
                objProcessor.pInsMeeting(meeting);
                return RedirectToAction("Index");
            }
            else
            {
                // there is something wrong with the data values
                return View(meeting);
            }
        }

        [HttpGet]
        public ViewResult Update()
        {
            return View(new CRS.Domain.ConcreteEntities.Meeting());
        }

        [HttpPost]
        public ActionResult Update(CRS.Domain.ConcreteEntities.Meeting meeting)
        {
            if (ModelState.IsValid)
            {
                CRS.Domain.ConcreteProcessors.ProcessMeetings objProcessor;
                objProcessor = new CRS.Domain.ConcreteProcessors.ProcessMeetings();
                objProcessor.pUpdMeetings(meeting);
                return RedirectToAction("Index");
            }
            else
            {
                // there is something wrong with the data values
                return View(meeting);
            }
        }

        [HttpGet]
        public ViewResult Delete()
        {
            return View(new CRS.Domain.ConcreteEntities.Meeting());
        }

        [HttpPost]
        public ActionResult Delete(CRS.Domain.ConcreteEntities.Meeting meeting)
        {
            
            if (ModelState.IsValid)
            {
                CRS.Domain.ConcreteProcessors.ProcessMeetings objProcessor;
                objProcessor = new CRS.Domain.ConcreteProcessors.ProcessMeetings();
                objProcessor.pDelMeetings(meeting);
                return RedirectToAction("Index");
            }
            else
            {
                // there is something wrong with the data values
                return View(meeting);
                //return View();
            }
        }
        
    }
}

CRS.WebUI/Views/Shared/_AdmAttendeesSummary.cshtml
@model CRS.Domain.ConcreteEntities.Attendee

<div class="well">
    <h3>
        <strong>@Model.AttendeeName</strong>
        <span class="pull-right label label-primary">@Model.AttendeeID.ToString()</span>
    </h3>
    <div class="pull-right">
        
    </div>
    <span class="label">@Model.AttendeeEmail</span>
    <span class="lead">@Model.AttendeePhone</span>
    
</div>

CRS.WebUI/Views/Shared/_AdmConferenceRoomsSummary.cshtml
@model CRS.Domain.ConcreteEntities.ConferenceRoom

<div class="well">
    <h3>
        <strong>@Model.ConferenceRoomFloor</strong>
        <span class="pull-right label label-primary">@Model.ConferenceRoomID.ToString()</span>
    </h3>
    @using (Html.BeginForm("AddToReservations", "Reservations"))
    {
        <div class="pull-right">
            @Html.HiddenFor(x => x.ConferenceRoomName) @*For Each ConferenceRoomID add a hidden element*@
            @*@Html.Hidden("ConferenceRoomID", Model.ConferenceRoomID)*@
            @Html.Hidden("returnUrl", Request.Url.PathAndQuery) @*a hidden element with an URL*@
            <input type="submit" class="btn btn-success" value="Book the room" />
        </div>

    }
    <span class="lead">@Model.ConferenceRoomLocation</span>
</div>

CRS.WebUI/Views/Shared/_AdmMeetingRoomAttendeeSummary.cshtml
@model CRS.Domain.ConcreteEntities.MeetingRoomAttendee

<div class="well">
    <h3>
        <strong>@Model.ConferenceRoomName</strong>
        <span class="pull-right label label-primary">@Model.ConferenceRoomID.ToString()</span>
    </h3>
    @*@using (Html.BeginForm("AddToReservations", "Reservations"))*@
    @*{*@
        @*<div class="pull-right">*@
            @*@Html.HiddenFor(x => x.ConferenceRoomName)*@ @*For Each ConferenceRoomID add a hidden element*@
            @*@Html.Hidden("ConferenceRoomID", Model.ConferenceRoomID)*@
            @*@Html.Hidden("returnUrl", Request.Url.PathAndQuery)*@ @*a hidden element with an URL*@
           @*<input type="submit" class="btn btn-success" value="Book the room" />*@
          @*</div>*@

    @*}*@
    <span class="lead">@Model.ConferenceRoomFloor</span>
    <span class="lead">@Model.ConferenceRoomLocation</span>
    <span class="lead">@Model.AttendeeID</span>
    <span class="lead">@Model.AttendeePhone</span>

    <span class="lead">@Model.MeetingID</span>
    <span class="lead">@Model.MeetingSubject</span>
    <span class="lead">@Model.MeetingHour</span>
    <span class="lead">@Model.MeetingDate</span>

</div>

CRS.WebUI/Views/Shared/_AdmMeetingsSummary.cshtml
@model CRS.Domain.ConcreteEntities.Meeting

<div class="well">
    <h3>
        <strong>@Model.MeetingDate</strong>
        @Model.ConferenceRoomID.ToString()
    </h3>
    @*@using (Html.BeginForm("AddToReservations", "Reservations"))*@
    @*{*@
        @*<div class="pull-right">*@
            @*@Html.HiddenFor(x => x.MeetingID)*@ @*For Each ConferenceRoomID add a hidden element*@
            @*@Html.Hidden("ConferenceRoomID", Model.ConferenceRoomID)*@
            @*@Html.Hidden("returnUrl", Request.Url.PathAndQuery)*@ @*a hidden element with an URL*@
            @*<input type="submit" class="btn btn-success" value="Book the room" />*@
        @*</div>*@

    @*}*@
    <div class="pull-right">
        @Html.ActionLink("Delete Meeting", "Delete", "Meetings", new {@Model.ConferenceRoomID}, new { @class = "btn-success" })
    </div>
  


    <span class="lead">@Model.MeetingDate</span>
</div>

CRS.WebUI/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" />
</head>
<body>
    @Html.Partial("~/Views/Nav/AdminNavBar.cshtml");
    <div class="container">
        @if (TempData["Message"] != null)
        {
            <div class="alert alert-success">@TempData["Message"]</div>
        }

        @if (TempData["EmailStatus"] != null)
        {
            <div class="alert alert-success">@TempData["EmailStatus"]</div>
        }
        @RenderBody()
    </div>
</body>
</html>

CRS.WebUI/Views/Shared/_AdminLayoutJWS.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle"
                        data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*@Html.ActionLink("Application name", "Index", "Home", null,
                                new { @class = "navbar-brand" })*@
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Meetings", "Index", "Meetings", null, new { @class = "btn btn-info btn-large" })</li>
                    <li>@Html.ActionLink("Conference Rooms", "Index", "ConferenceRooms", null, new { @class = "btn btn-info btn-large" })</li>
                    <li>@Html.ActionLink("Attendees", "Index", "Attendees", null, new { @class = "btn btn-info btn-large" })</li>
                    <li>@Html.ActionLink("Meeting Room Attendees", "Index", "MeetingRoomAttendees", null, new { @class = "btn btn-info btn-large" })</li>
                </ul>
                @*@Html.Partial("_LoginPartial")*@
            </div>
        </div>
    </div>
        @RenderBody()

    <footer>
        <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
    </footer>
</body>
</html>

CRS.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" />
</head>
<body>
    @Html.Partial("~/Views/Nav/UserNavBar.cshtml");
    <div class="container">
        @if (TempData["Message"] != null)
        {
            <div class="alert alert-success">@TempData["Message"]</div>
        }
        @RenderBody()
    </div>
</body>
</html>